name: Staging Deployment 

on: 
  push: 
    branches: 
      - 'staging'
  pull_request:
    branches:
      - 'staging'
    types: 
      - 'closed'

jobs:
  deploy: 
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Deploying into On-Premise Server 
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          password: ${{secrets.SERVER_PASSWORD}}
          port: ${{secrets.SERVER_PORT}}
          script: |
             cd ~/E-Learning-API
             ./deploy.sh
